import Head from "next/head";

import { useContext } from "react";
import { DefaultContext } from "../context/context";

export default function Home() {
    const { value, setValue } = useContext(DefaultContext);

    return (
        <>
            <Head>
                <title>NextJS Tailwind CSS Template</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="text-3xl font-bold underline">{value}</h1>
            </main>
        </>
    );
}
