import Head from "next/head";

import { useContext } from "react";
import { DefaultContext } from "../context/context";

import { Intro } from "@/components/Intro/Intro";
import { Featured} from "@/components/Offers/Featured";
import { Offers } from "@/components/Offers/Offers";

export default function Home() {
    const { value, setValue } = useContext(DefaultContext);

    return (
        <>
            <Head>
                <title>NextJS Tailwind CSS Template</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${{}} bg-slate-800`}>
                <Intro/>
                <Featured/>
                <Offers/>
            </main>
        </>
    );
}
